name: CI

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - 'README.md'
      - '.gitignore'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Test
      run: ./jdkw-impl.sh ./gradlew test
